### ISSUE TITLE
StatusBarOverlay.defaultBackgroundColor is not Working

### ISSUE THREAD

**Issue by merovic** [IdleHandsApps/StatusBarOverlay#2]
StatusBarOverlay.defaultBackgroundColor has no effect at all and it keeps black what is the problem ??

**Comment by fraserscottmorrison** [comment]
Could be a bug - have you debugged it?

**Comment by merovic** [comment]
yes and everything else works as expected including defaultTextColor, only backgroundColor has no effect

**Comment by fraserscottmorrison** [comment]
Checked in a fix for this, cheers
