### ISSUE TITLE
Not detecting offline when airplane mode on before launching

### ISSUE THREAD

**Issue by avi-midtown** [IdleHandsApps/StatusBarOverlay#3]
# Steps to reproduce

1. Make sure the app process is stopped (force close if needed).
2. Turn airplane mode on.
3. Launch the app.
4. Expect to see status "No internet connection", but nothing happens.
5. Turn airplane mode off, then back on (while app's still running).
6. Now status is visible.

**Comment by avi-midtown** [comment]
After inspecting runtime behavior, it seems like the AlamoFire callback is not called with the initial state. Maybe should call manually `networkStatusChanged(reachability!.networkReachabilityStatus, animated: true)` for the first time.

**Comment by fraserscottmorrison** [comment]
With the demo project it was working fine, but yes on other projects I could reproduce it.

Thanks for raising - Ive just pushed out a fix
