### ISSUE TITLE
Swift Package Manager error

### ISSUE THREAD

**Issue by marcheimendinger** [IdleHandsApps/StatusBarOverlay#8]
When using SPM in Xcode to get the library, I have this error :

<img width="585" alt="Screenshot 2020-02-16 at 11 36 28" src="https://user-images.githubusercontent.com/43568598/74603213-850ee200-50b1-11ea-95f6-38d3a3d93193.png">

**Comment by iciorba** [comment]
Getting the same thing.

**Comment by fraserscottmorrison** [comment]
Fixed In version 3.1.0
Cheers
